# mypy: ignore-errors
"""automatic created_at on users table

Revision ID: 386ee8c76d62
Revises: faa71b5af05a
Create Date: 2026-08-15 16:16:07.447497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "386ee8c76d62"
down_revision: Union[str, Sequence[str], None] = "faa71b5af05a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.DateTime(),
        existing_nullable=False,
        server_default=sa.text("now()"),
        postgresql_using="created_at::timestamp without time zone",
    ),
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
