name: Server CI Pipeline

on:
  push:
    paths:
      - "server/**"

env:
  GH_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
  GH_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
  GH_REDIRECT_URI: ${{ secrets.GITHUB_REDIRECT_URI }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  PSGRE_USER: ${{ secrets.PSGRE_USER }}
  PSGRE_PASSWORD: ${{ secrets.PSGRE_PASSWORD }}
  PSGRE_HOST: ${{ secrets.PSGRE_HOST }}
  PSGRE_PORT: ${{ secrets.PSGRE_PORT }}
  PSGRE_DB: ${{ secrets.PSGRE_DB }}
  DEBUG: "False"

jobs:
  black:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m black --check .

  mypy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m mypy .

  test-unit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m pytest -m unit

  test-integration:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server
  
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m pytest -m integration