name: Server CI Pipeline

on:
  push:
    paths:
      - "server/**"

env:
  GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  GH_REDIRECT_URI: ${{ secrets.GH_REDIRECT_URI }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  DEBUG: "False"

jobs:
  black:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m black --check .

  mypy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m mypy .

  test-unit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m pytest -m unit

  test-integration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.PSGRE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PSGRE_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.PSGRE_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PSGRE_USER: ${{ secrets.PSGRE_USER }}
      PSGRE_PASSWORD: ${{ secrets.PSGRE_PASSWORD }}
      PSGRE_DB: ${{ secrets.PSGRE_DB }}
      PSGRE_HOST: localhost
      PSGRE_PORT: 5432
    
    defaults:
      run:
        working-directory: server
  
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync

      - run: uv run python -m pytest -m integration